build:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - flutter pub get
    - flutter gen-l10n
  script:
    - flutter build web --base-href /portfolio/
  artifacts:
    paths:
      - build/web

deploy:
  stage: deploy
  script:
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - master