build:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - flutter pub get
    - flutter gen-l10n
  script:
    - flutter build web --base-href /portfolio/ --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID --dart-define=FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID --dart-define=FIREBASE_SENDER_ID=$FIREBASE_SENDER_ID
  artifacts:
    paths:
      - build/web

pages:
  stage: deploy
  script:
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - master