name: portfolio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  ###### FireFlutter ######
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4

  ###### NAVIGATION & INJECTION ######
  flutter_modular: ^5.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  modular_bloc_bind: ^1.0.1

  ###### DESIGN ######
  lottie: ^1.2.1
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  flutter_svg: ^1.1.1+1
  flutter_layout_grid: ^2.0.1
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.2.2
  favicon: ^1.0.15
  flutter_screenutil: ^5.6.0

  ###### UTILS ######

  intl: 0.17.0
  logger: ^1.1.0
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  faker: ^2.0.0


  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter




dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.0.1
  lint: ^1.0.0
  dart_code_metrics: ^4.8.1
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/jpg/
    - assets/svg/
    - assets/svg/social/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: DMSans
      fonts:
        - asset: fonts/dm_sans/DMSans-Medium.ttf
          weight: 200
        - asset: fonts/dm_sans/DMSans-Regular.ttf
          weight: 400
        - asset: fonts/dm_sans/DMSans-Bold.ttf
          weight: 700